name: rclone-restic-backup
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Dropbox
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.RSYNC_HOST}}
          command_timeout: # optional, default is 10m
          username: ${{secrets.RSYNC_USERNAME}}
          key: ${{secrets.RSYNC_KEY}}
          script: "rclone sync --checksum --stats-log-level=NOTICE dropbox: backup/dropbox"
          # Stop the script after the first failure.
          script_stop: # optional
          # Environment variables to be passed to the shell script.
          envs: # optional

